### ISSUE TITLE
Transmit only and receive only definitions appear to be swapped from the ANT spec

### ISSUE THREAD

**Issue by sharoldsen** [cujomalainey/ant-arduino#46]
Transmit only and receive only definitions appear to be swapped from the ANT spec.

#define CHANNEL_TYPE_UNIDIRECTIONAL_RECEIVE   0x50
#define CHANNEL_TYPE_UNIDIRECTIONAL_TRANSMIT  0x40

From Table 5-1. ANT channel types
0x40
Slave Receive Only Channel (diagnostic)

0x50
Master Transmit Only Channel (legacy)

**Comment by cujomalainey** [comment]
Thanks for catching this, you are correct, I'll do a hotfix and a release right now.
