### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [cujomalainey/ant-arduino#48]
Hi @cujomalainey 

we have detected that you changed the name of the library in `library.properties` from
  `ANT-Arduino library`
to
  `ANT-Arduino`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `ANT-Arduino`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 595 - 2018/01/15 15:43:15 Scraping https://github.com/cujomalainey/ant-arduino.git
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 0.1.0
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino library:0.1.0 already loaded, skipping
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 0.1.1
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino library:0.1.1 already loaded, skipping
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 0.2.0
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino library:0.2.0 already loaded, skipping
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 0.3.0
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino:0.3.0 has wrong library name, should be ANT-Arduino library
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 1.0.0
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino:1.0.0 has wrong library name, should be ANT-Arduino library
JOB 595 - 2018/01/15 15:43:16 Checking out tag: 1.0.1
JOB 595 - 2018/01/15 15:43:16 Release ANT-Arduino:1.0.1 has wrong library name, should be ANT-Arduino library
```

See also: https://github.com/arduino/Arduino/issues/7127

**Comment by cujomalainey** [comment]
Hello @cmaglie 

Yes, please use `ANT-Arduino` for the library
