### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by usrstephan** [cujomalainey/ant-arduino#54]
The NRF51 is a specialized BLE chip - but it is possible to use this library with the ESP32 or are any functions missing?
Does anyone have success/experience with that combination?

**Comment by cujomalainey** [comment]
Garmin/Dynastream only deploys the radio stack through nordicsemi so currently it only works on nRFs unfortunately. The ESP32 must use an external nRF to run ANT for it unfortunately. See the serial and spi drivers for the interfacing implementation. Please feel free to reopen if you have any more questions.
