### ISSUE TITLE
Please include Apache NuttX RTOS in the roadmap

### ISSUE THREAD

**Issue by acassis** [cujomalainey/ant-arduino#59]
Hi Curtis,
It should be nice if you consider including support to NuttX RTOS in your ant-arduino

NuttX is a Unix and Linux-like RTOS used by many companies like Fitbit, Xiaomi, Sony, etc

It was used by JAXA probe in the moon: https://developer.sony.com/posts/apache-nuttx-powers-worlds-smallest-lunar-robot-in-japans-historic-autonomous-lunar-exploration-mission

There is a port to nRF51 here: https://github.com/SaitoYutaka/incubator-nuttx

I the NuttX mainline there is support to nRF52, nRF53 and nRF91: https://github.com/apache/nuttx

**Comment by cujomalainey** [comment]
Unfortunately am pretty short on time and I have a number of people waiting for [ant-rs](https://github.com/cujomalainey/ant-rs) 0.01 release which has already been very delayed. That being said, the level or work to implement the abstraction for NuttX is relatively small if you want to add it yourself I will review and merge it.

Serial implementation [example](https://github.com/cujomalainey/ant-arduino/blob/master/src/MainClasses/ANT_ArduinoSerialAnt.cpp)

Softdevice [implementation](https://github.com/cujomalainey/ant-arduino/blob/master/src/MainClasses/ANT_ArduinoNativeAnt.cpp)

**Comment by acassis** [comment]
Hi @cujomalainey thank you very much!

Ok, I will try to submit that nRF51 to mainline, when if you remember of NuttX in the future, it will be easier to do.

I'll close this Issue now. Thank you again!
